### ISSUE TITLE
Usage examples - "type" syntax

### ISSUE THREAD

**Issue by mariov652** [StewLG/check_truenas_extended_play#1]
Thank you for your effort to imporove on the original and maintain this.  My first comment/issue submission, so I trust this is ok..

Very minor issue - the Usage examples are shown using "-type", however this only works with the syntax shown in the optional arguments as: "-t" or "--type".

./check_truenas_extended_play.py -H <host> -u <user> -p <pwd> -type zpool -nv --zpoolname RAID10Pool
usage: check_truenas_extended_play.py [-h] -H HOSTNAME -u USER -p PASSWD -t
                                      TYPE [-pn ZPOOLNAME] [-ns] [-nv] [-ig]
                                      [-d]
check_truenas_extended_play.py: error: unrecognized arguments: zpool

**Comment by StewLG** [comment]
Thank you for catching this. I've corrected the documentation.

Let me know if you have any other issues.
