### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by juleslink** [StewLG/check_truenas_extended_play#15]
hey there,

i think you got a typo here, 

https://github.com/StewLG/check_truenas_extended_play/blob/5333cbfdb00d6509d293dfd7a3e97204e2bdc19b/check_truenas_extended_play.py#L375

If i change it to 

        BYTES_IN_MEGABYTE = 1024 * 1024;

it matches exactly the displayed values in TrueNas Scale.

Best,
jules

**Comment by StewLG** [comment]
You're completely right. Amazing it took this long to find!

I've made the change and updated version numbers and documentation. If you could pull it, let me know what you think. Once you're happy I'll close the issue.

**Comment by StewLG** [comment]
I am assuming by the lack of comment that you are satisfied with my change. I'm going to close this issue, but feel free to re-open it or make another issue if needed.

Thank you again for finding this, I think I never would have noticed this otherwise.
