### ISSUE TITLE
Used space pool (in percent %)

### ISSUE THREAD

**Issue by Cosmits** [StewLG/check_truenas_extended_play#4]
Please help me.

1) I want to add   (--type TYPE  Type of check)  Used space pool disk  (in percent %) or used and free space in Gbyte

2) Where is documents  API v2.0 in internet ? 
http://treuNAS/api/docs/   - This url in't work in my  TrueNAS-12.0-U4

**Comment by Cosmits** [comment]
1) I m add   --type  disks
[check_truenas_extended_play.zip](https://github.com/StewLG/check_truenas_extended_play/files/6625302/check_truenas_extended_play.zip)

2)API  REST https://www.truenas.com/docs/api/rest.html

**Comment by StewLG** [comment]
This request has been handled with the following PR:

https://github.com/StewLG/check_truenas_extended_play/pull/9
