### ISSUE TITLE
Feature Request: Add Update Checking

### ISSUE THREAD

**Issue by madtempest** [StewLG/check_truenas_extended_play#6]
Hi,

I really like that this plugin does everything I want it to for Pools, but it'd be great if it also did update checks to help consolidate it as a more "all in one" type solution.

Thanks!

**Comment by StewLG** [comment]
This is a very reasonable suggestion, thank you for it.

I've implemented it here:

https://github.com/StewLG/check_truenas_extended_play/tree/update_check

There's a PR here, but I'll wait a bit for feedback from you before merging it:

https://github.com/StewLG/check_truenas_extended_play/pull/8

All issues with updates are treated as warnings, not errors. But if you disagree with this choice, try to explain your perspective and convince me.

Let me know what you think.

**Comment by StewLG** [comment]
This has been completed with this PR:

https://github.com/StewLG/check_truenas_extended_play/pull/8

Please let me know if this doesn't meet your needs.

**Comment by madtempest** [comment]
Hi @StewLG sorry for the delayed reply.

This works as expected. 

Thank you for implementing this and the API key!

**Comment by StewLG** [comment]
You're welcome. There's also a pool capacity check coming:

https://github.com/StewLG/check_truenas_extended_play/pull/9

I expect this to drop tomorrow. Feedback appreciated if you have time.
